### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by vanh17** [vanh17/SnoopCH#1]

**Comment by vanh17** [comment]
let float = (digit+ '.'? | digit\* frac) exp?
Could you explain more for me about this syntax? What does _?_ mean? And it looks like we cannot type negative number in the compiler dont we? Thank you Dr. @skiadas 
Warmest,
Hoang

**Comment by skiadas** [comment]
That's regular expressions. Have you read about regular expressions?

**Comment by vanh17** [comment]
May be it is too long ago so I forgot it. I will reread it. Thank you

**Comment by skiadas** [comment]
http://caml.inria.fr/pub/docs/manual-ocaml/lexyacc.html

**Comment by vanh17** [comment]
I found that website and now reading it :)). Thank you so much Dr.

**Comment by vanh17** [comment]
Need fraction class.

**Comment by vanh17** [comment]
Dear Dr. @skiadas ,
so if $1 is the pair, how can you break them into two parts? Thank you

**Comment by skiadas** [comment]
It's a Ocaml pair. You could even do a pattern match on it, you can treat it as a OCaml expression.

You can also use it as is, why do you need to break it?

**Comment by vanh17** [comment]
so I try to work on the FracS, and now my FRAC will take in a pair like this
<int * int> FRAC, then i need to break $1 in two value so that I can pass it to FracS.
something like
| FRAC      { FracS ($1_firstpart, $1_secondpart)

**Comment by vanh17** [comment]
got it :)

**Comment by skiadas** [comment]
Right, you basically have a pair, then you want to break it into its parts then put the parts back as a pair again ....   It's _already_ a pair!

**Comment by skiadas** [comment]
Did you try to just use $1 itself, like `FracS $1`?

**Comment by vanh17** [comment]
I tried again, but it is still give me the same error with only $1. It is weird, ?-? So I put { FracS $1 }
And it said the contructor FracS expects 2 arguments but is applied 1 arguments.

**Comment by vanh17** [comment]
Fraction done, Update and close Arithmetic, now we can add fraction with itself, int, float.
Next step: complex number.

**Comment by skiadas** [comment]
So, it turns out if you put, in both your types files, parentheses around the `int*int`  :     `| FracS of (int * int)` then it should not be giving you that warning any more. It shouldn't have been necessary, but it is.

Btw, if you read the 12.2.6 section in http://caml.inria.fr/pub/docs/manual-ocaml-4.00/manual026.html carefully you will be able to make the line for frac in your lexer a lot easier, by matching in one variable the part to the left of the fraction and in another variable the part to the right of the function. Then the right hand side on that line can be as simple as `{ FRAC (int_of_string x, int_of_string y) }`

**Comment by vanh17** [comment]
ocaml int_of_string arent happy with this "+", so I think we have change FRAC a little bit though

**Comment by skiadas** [comment]
Match three things then, and ignore the sign.

**Comment by vanh17** [comment]
so if we ignore the sign, then we cannot have negative fraction. I might keep it as the same, and come back later when have time.

**Comment by skiadas** [comment]
Then don't ignore the sign, use it in your evaluation of the numerator. Point is you can match the three parts in three variables, and do the appropriate thing, rather than grabbing the whole thing in one variable and trying to do substring math.

**Comment by vanh17** [comment]
actually I think of the great way to deal with the sign. int_of_string is not happy with "+" but float_of_string is indifferent, so I decide to int_of_float (float_of_string s).

**Comment by vanh17** [comment]
Implemented complex....
Long one, but it takes care of all cases.
Will update arithmetic later and move on too cond :)))

**Comment by vanh17** [comment]
Bombard your email message.

**Comment by vanh17** [comment]
a little messy in the code in lexer, but I guess I will keep it like that at this time. Will clean the whole thing up in the end while have time.
Bombarding email message 2.

**Comment by vanh17** [comment]
Add more Arith for Complex

**Comment by vanh17** [comment]
Arithmetic for complex.

**Comment by vanh17** [comment]
All tests passed for Numbers.
