### ISSUE TITLE
Fun

### ISSUE THREAD

**Issue by vanh17** [vanh17/SnoopCH#16]
Implementing function

**Comment by vanh17** [comment]
Do you know what is the type of the fun in the ocaml?
I try to do something like FunS of exprS ->exprS but it is not happy about the syntax.
Warmest,
Dr.@skiadas

**Comment by skiadas** [comment]
That should work, maybe after you put parentheses around the (exprS -> exprS).

But I don't think that's what you want for your function type. Look at all the function types we've implemented. Nowhere did we use the implementation language's meaning of function.

**Comment by vanh17** [comment]
=))) parenthises issues lol. Thank you so much Dr. @skiadas , at least my guess was right

**Comment by vanh17** [comment]
Dear Dr. @skiadas ,
Can you look at my code about the Fun? I try to pass the value of FunC which is FunC (arg->r) so that I can interp arg and r separtely. but dont let me do this matching pattern.
Thank you so much

**Comment by skiadas** [comment]
I told you already, you shouldn't be trying to put it as a function. It should be a pair, or triple or however many things a FunS or FunC needs to keep around. What are you asking it to match exactly?

**Comment by vanh17** [comment]
That should be a better solution I guess. Thank you Dr. Skiadas!
