### ISSUE TITLE
Cond-lexer-parser

### ISSUE THREAD

**Issue by vanh17** [vanh17/SnoopCH#6]

**Comment by vanh17** [comment]
Is there any way that we can test file for compiler rather than just typing in the code in the console?
Warmest,
Dr. @skiadas

**Comment by skiadas** [comment]
If you have a test file, i.e. a program written in your language, and your language's executable is called `snoopch` or whatnot, then at least on unix-like systems you could do: `snoopch < filename` and it will run the `snoopch` file reading input from the filename. And you could do `snoopch < filename > outname` to have the output written on another file if you like. I don't know what the corresponding syntax for windows is, but the task is to "read standard input from a file".

**Comment by vanh17** [comment]
for the cond, I am thinking is there any way that we could receive a lot of input like this 
COND (OSB expr expr CSB)+.
So I decide to build CondS as a list of pair of expession. now the parxer and lexer is really a 
headache

**Comment by skiadas** [comment]
The lexer shouldn't have to do much, it just reports tokens. It's the parser that would need to do work, matching: open paren, the COND word, then a "list of expr pairs" and then a close paren.

Then the "list of expr pairs" is another rule, like the "main", "expr"  and "headex" rules, and it captures one or more pairs of expressions and forms a list out of them. So you'll need to create a new set of rules, named something like "expr_pair_list". That does the "one or more ..." or whatever you need it to do. Each time you need a repeatable part with a specified form, you may need to create a new set of rules. In the language of Theory of Computation context-free grammars, you would be creating a new non-terminal.

**Comment by vanh17** [comment]
ah ha. It is cool.

**Comment by vanh17** [comment]
Even though the complex work well, I still think it create a bunch of work to clean up. Is there any possible way to clean the messy code up? Thank you Dr. @skiadas 
Warmest

**Comment by skiadas** [comment]
There might be some things that can be done, nothing particularly straightforward though. That's one of the things I usually create and issue for and only come back to if I have time.

**Comment by vanh17** [comment]
for the listofpair rule, do you mean something like this 

listPairExpr:  
  | pairExpr :: listPairExpr     { $1 }
;

pairExpr:
  | (expr, expr)                 { $1 }
;
I commit the code so you probably can see it.

**Comment by skiadas** [comment]
Basically yes. But of course when you say a "pairExpr" you mean "an open paren, then an expression, then another expression, then a close paren" and what you would be returning in the right-hand-side would be an OCAML pair. Similarly the listPairExpr is supposed to look for "a pairExpr followed by a listPairExpr" and it is supposed to return a list. You also need some "stopping case".

**Comment by vanh17** [comment]
Cond up now work with as many pair as user want.

**Comment by vanh17** [comment]
All tests passed!
